@extends('layouts.app')

@section('title','Services')

@section('content')
<section id="services">
    <h1>Product</h1>
    <table>
        <tr>
            <th>Product Name</th>
            <th>Price</th>
            <th>Quantity</th>
        </tr>
        @php
            $products = [
                ['name' => 'Apple', 'price' => 1.00, 'quantity' => 50],
                ['name' => 'Banana', 'price' => 0.50, 'quantity' => 50],
                ['name' => 'Cherry', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Date', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Elderberry', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Fig', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Grape', 'price' => 2.20, 'quantity' => 50],
                ['name' => 'Honeydew', 'price' => 3.50, 'quantity' => 50],
                ['name' => 'Indian Fig', 'price' => 2.80, 'quantity' => 50],
                ['name' => 'Jackfruit', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Kiwi', 'price' => 1.20, 'quantity' => 50],
                ['name' => 'Lemon', 'price' => 0.70, 'quantity' => 50],
                ['name' => 'Mango', 'price' => 1.80, 'quantity' => 50],
                ['name' => 'Nectarine', 'price' => 2.10, 'quantity' => 50],
                ['name' => 'Orange', 'price' => 1.00, 'quantity' => 50],
                ['name' => 'Papaya', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Pear', 'price' => 1.10, 'quantity' => 50],
                ['name' => 'Pineapple', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Plum', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Raspberry', 'price' => 3.20, 'quantity' => 50],
                ['name' => 'Strawberry', 'price' => 2.80, 'quantity' => 50],
                ['name' => 'Watermelon', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Apricot', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Blackberry', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Blueberry', 'price' => 3.50, 'quantity' => 50],
                ['name' => 'Cantaloupe', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Coconut', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Dragonfruit', 'price' => 5.00, 'quantity' => 50],
                ['name' => 'Guava', 'price' => 1.80, 'quantity' => 50],
                ['name' => 'Lychee', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'Pomegranate', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Persimmon', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Prickly Pear', 'price' => 3.80, 'quantity' => 50],
                ['name' => 'Quince', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Rhubarb', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Starfruit', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Tangerine', 'price' => 2.20, 'quantity' => 50],
                ['name' => 'Pluot', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Ugni', 'price' => 5.00, 'quantity' => 50],
                ['name' => 'Xigua', 'price' => 3.50, 'quantity' => 50],
                ['name' => 'Zinfandel Grape', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Acai', 'price' => 5.50, 'quantity' => 50],
                ['name' => 'Amaranth', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Avocado', 'price' => 1.90, 'quantity' => 50],
                ['name' => 'Bael', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Bilberry', 'price' => 3.80, 'quantity' => 50],
                ['name' => 'Boysenberry', 'price' => 3.30, 'quantity' => 50],
                ['name' => 'Carambola', 'price' => 4.20, 'quantity' => 50],
                ['name' => 'Cashew Apple', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Cherimoya', 'price' => 3.50, 'quantity' => 50],
                ['name' => 'Clementine', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Custard Apple', 'price' => 3.60, 'quantity' => 50],
                ['name' => 'Feijoa', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Galia Melon', 'price' => 2.60, 'quantity' => 50],
                ['name' => 'Jabuticaba', 'price' => 5.00, 'quantity' => 50],
                ['name' => 'Longan', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Mangosteen', 'price' => 5.50, 'quantity' => 50],
                ['name' => 'Mulberry', 'price' => 3.40, 'quantity' => 50],
                ['name' => 'Olives', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Pawpaw', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Plumcot', 'price' => 2.80, 'quantity' => 50],
                ['name' => 'Salak', 'price' => 4.20, 'quantity' => 50],
                ['name' => 'Soursop', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'White Sapote', 'price' => 3.90, 'quantity' => 50],
                ['name' => 'Ziziphus', 'price' => 3.70, 'quantity' => 50],
                ['name' => 'Jackfruit', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Papaya', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Dragonfruit', 'price' => 5.00, 'quantity' => 50],
                ['name' => 'Plum', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Pineapple', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Nectarine', 'price' => 2.10, 'quantity' => 50],
                ['name' => 'Strawberry', 'price' => 2.80, 'quantity' => 50],
                ['name' => 'Grape', 'price' => 2.20, 'quantity' => 50],
                ['name' => 'Cantaloupe', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Kiwi', 'price' => 1.20, 'quantity' => 50],
                ['name' => 'Tangerine', 'price' => 2.20, 'quantity' => 50],
                ['name' => 'Coconut', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Mango', 'price' => 1.80, 'quantity' => 50],
                ['name' => 'Lychee', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'Watermelon', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Pomegranate', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Persimmon', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Apricot', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Pluot', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Acai', 'price' => 5.50, 'quantity' => 50],
                ['name' => 'Bilberry', 'price' => 3.80, 'quantity' => 50],
                ['name' => 'Blueberry', 'price' => 3.50, 'quantity' => 50],
                ['name' => 'Boysenberry', 'price' => 3.30, 'quantity' => 50],
                ['name' => 'Clementine', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Feijoa', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Starfruit', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Salak', 'price' => 4.20, 'quantity' => 50],
                ['name' => 'White Sapote', 'price' => 3.90, 'quantity' => 50],
                ['name' => 'Soursop', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'Ziziphus', 'price' => 3.70, 'quantity' => 50],
                ['name' => 'Plumcot', 'price' => 2.80, 'quantity' => 50],
                ['name' => 'Salak', 'price' => 4.20, 'quantity' => 50],
                ['name' => 'Soursop', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'White Sapote', 'price' => 3.90, 'quantity' => 50],
                ['name' => 'Ziziphus', 'price' => 3.70, 'quantity' => 50],
                ['name' => 'Jackfruit', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Papaya', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Dragonfruit', 'price' => 5.00, 'quantity' => 50],
                ['name' => 'Plum', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Pineapple', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Nectarine', 'price' => 2.10, 'quantity' => 50],
                ['name' => 'Strawberry', 'price' => 2.80, 'quantity' => 50],
                ['name' => 'Grape', 'price' => 2.20, 'quantity' => 50],
                ['name' => 'Cantaloupe', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Kiwi', 'price' => 1.20, 'quantity' => 50],
                ['name' => 'Tangerine', 'price' => 2.20, 'quantity' => 50],
                ['name' => 'Coconut', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Mango', 'price' => 1.80, 'quantity' => 50],
                ['name' => 'Lychee', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'Watermelon', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Pomegranate', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Persimmon', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Apricot', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Cherimoya', 'price' => 3.50, 'quantity' => 50],
                ['name' => 'Clementine', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Custard Apple', 'price' => 3.60, 'quantity' => 50],
                ['name' => 'Feijoa', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Galia Melon', 'price' => 2.60, 'quantity' => 50],
                ['name' => 'Pomegranate', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Persimmon', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Apricot', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Pluot', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Acai', 'price' => 5.50, 'quantity' => 50],
                ['name' => 'Bilberry', 'price' => 3.80, 'quantity' => 50],
                ['name' => 'Blueberry', 'price' => 3.50, 'quantity' => 50],
                ['name' => 'Boysenberry', 'price' => 3.30, 'quantity' => 50],
                ['name' => 'Clementine', 'price' => 2.30, 'quantity' => 50],
                ['name' => 'Feijoa', 'price' => 3.00, 'quantity' => 50],
                ['name' => 'Starfruit', 'price' => 4.00, 'quantity' => 50],
                ['name' => 'Salak', 'price' => 4.20, 'quantity' => 50],
                ['name' => 'White Sapote', 'price' => 3.90, 'quantity' => 50],
                ['name' => 'Soursop', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'Ziziphus', 'price' => 3.70, 'quantity' => 50],
                ['name' => 'Plumcot', 'price' => 2.80, 'quantity' => 50],
                ['name' => 'Salak', 'price' => 4.20, 'quantity' => 50],
                ['name' => 'Soursop', 'price' => 4.50, 'quantity' => 50],
                ['name' => 'White Sapote', 'price' => 3.90, 'quantity' => 50],
                ['name' => 'Ziziphus', 'price' => 3.70, 'quantity' => 50],
                ['name' => 'Jackfruit', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Papaya', 'price' => 1.50, 'quantity' => 50],
                ['name' => 'Dragonfruit', 'price' => 5.00, 'quantity' => 50],
                ['name' => 'Plum', 'price' => 2.00, 'quantity' => 50],
                ['name' => 'Pineapple', 'price' => 2.50, 'quantity' => 50],
                ['name' => 'Nectarine', 'price' => 2.10, 'quantity' => 50],
                ['name' => 'Ziziphus', 'price' => 3.70, 'quantity' => 50]
            ];
        @endphp

        @foreach($products as $index => $product)
            <tr class="product">
                <td>{{ $index + 1}}</td>
                <td>{{ $product['name'] }}</td>
                <td>${{ number_format($product['price'], 2) }}</td>
                <td>{{ $product['quantity'] }}</td>
            </tr>
        @endforeach
    </table>
</section>
@endsection
